### ISSUE TITLE
How can I use this tool ?

### ISSUE THREAD

**Issue by Denver3D** [TyphoidHippo/Warframe-DPS-Tool#1]
Hello,

I'm sorry I didn't know how I can use this wonderful tool can you help me please ? and thank you

**Comment by TyphoidHippo** [comment]
Hey, sorry I didn't notice this before.

I'll add a project that zips up the binaries, stay tuned....

You can download/clone the repo and build from source right now, of course.

**Comment by TyphoidHippo** [comment]
Ok, I added a packager to the project - you can just download WarframeDPSTool.zip now.

https://github.com/TyphoidHippo/Warframe-DPS-Tool/blob/master/WarframeDPSTool.zip?raw=true

Enjoy :)
